[goldmark]
[goldmark.renderer]
unsafe = true
[goldmark.extensions]
[goldmark.extensions.passthrough]
enable = true
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[highlight]
noClasses = false
# codeFences = true
# guessSyntax = false
# hl_Lines = ""
# lineNoStart = 1
# lineNos = false
# lineNumbersInTable = true
# noClasses = true
# tabWidth = 2
# style = "github-dark"

[tableOfContents]
startLevel = 2
endLevel = 4
