[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

# [[main]]
# name = "Categories"
# pageRef = "categories"
# weight = 20

# [[main]]
# name = "Tags"
# pageRef = "tags"
# weight = 20

[[main]]
identifier = "search"
weight = 99
[main.params]
action = "search"

[[main]]
identifier = "locale"
weight = 100
[main.params]
action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
