baseURL = "https://leonh.fr"
languageCode = "en-us"
title = "leon h"

[pagination]
pagerSize = 5

[params]
author = "Leon Hollender"
description = "The blog of an architect (as in, buildings) turned software engineer."
copyright = "Say hi: <a href=\"mailto:hello@leonh.fr\" rel=\"me\">hello@leonh.fr</a><br />All content is published under the <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0</a> license."
dateFormat = "Jan 02, 2006"
style = "dark-without-switcher"
paginationSinglePost = true
readMore = false
copyCodeButton = true
rssAsSocialIcon = true

utterancesRepo = "leonhfr/blog"
utterancesTheme = "github-dark"
utterancesIssue = "pathname"

umamiId = "a8946b2c-9fa8-4520-a0f0-8debfbe43f0a"

[params.webmentions]
login = "leonh.fr"
pingback = true

[permalinks]
posts = "/:title/"

[outputs]
home = ["html", "rss", "json"]

[[params.social]]
id = "github"
url = "https://github.com/leonhfr"

[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/leonhollender"

[menu]
[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 1

# [[menu.main]]
#   identifier = "tags"
#   name = "tags"
#   url = "/tags/"
#   weight = 2

[[menu.main]]
identifier = "archive"
name = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2
style = "github-dark"
